spring:
  application:
    name: weather-now

server:
  port: 8080

openweathermap:
  api-key: ${OPENWEATHERMAP_API_KEY}
  geocoding-url: https://api.openweathermap.org/geo/1.0/direct
  weather-url: https://api.openweathermap.org/data/2.5/weather
  units: metric

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      probes:
        enabled: true
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    dev.sagar.weather: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG